### Hae kaikki henkilöt
GET http://localhost:3001/api/persons

### Info-sivu
GET http://localhost:3001/info

### Hae yksittäinen henkilö
GET http://localhost:3001/api/persons/2

### Hae olematon henkilö (odotettu vastaus: 404)
GET http://localhost:3001/api/persons/999

### Poista henkilö (odotettu vastaus: 204)
DELETE http://localhost:3001/api/persons/2

### Tarkista poiston jälkeen (odotettu vastaus: 404)
GET http://localhost:3001/api/persons/2

### Lisää uusi henkilö
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Liisa Lovelace",
  "number": "045-1234567"
}

### Lisäys ilman nimeä (odotettu vastaus: 400)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "045-1234567"
}

### Lisäys ilman numeroa (odotettu vastaus: 400)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Kalle Kukkonen"
}

### Lisäys jo olemassa olevalla nimellä (odotettu vastaus: 400)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "045-0000000"
}
