### Hae kaikki henkilöt
GET http://localhost:3001/api/persons

### Info-sivu
GET http://localhost:3001/info

### Hae yksittäinen henkilö
GET http://localhost:3001/api/persons/507f1f77bcf86cd799439011

### Hae olematon henkilö (odotettu vastaus: 404)
GET http://localhost:3001/api/persons/000000000000000000000000

### Väärän muotoinen id (odotettu vastaus: 400)
GET http://localhost:3001/api/persons/xyz

### Lisää uusi henkilö
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Liisa Lovelace",
  "number": "045-1234567"
}

### Lisäys ilman nimeä (odotettu vastaus: 400)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "045-1234567"
}

### Lisäys liian lyhyellä nimellä (odotettu vastaus: 400)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Ab",
  "number": "045-1234567"
}

### Poista henkilö (odotettu vastaus: 204)
DELETE http://localhost:3001/api/persons/507f1f77bcf86cd799439011

### Päivitä henkilön numero
PUT http://localhost:3001/api/persons/507f1f77bcf86cd799439011
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "045-9999999"
}
